version: '3'

services:
  nginx:
    build: ./nginx
    ports:
     - "80:80"
    depends_on:
      - php
    volumes:
      - ./www/html:/var/www/html

  php:
    build: ./php
    ports:
      - "9000:9000"
    volumes:
      - ./www/html:/var/www/html
