version: '3'

services:
  proxy:
    build: ./nginx-proxy
    ports:
      - 80:80
      - 443:443
    links:
      - nginx
    restart: always

  nginx:
    build: ./nginx
    expose:
     - "8080"
    depends_on:
      - php
    volumes:
      - ./www/html:/var/www/html
    restart: always

  php:
    image: php:fpm-alpine
    ports:
      - "9000:9000"
    volumes:
      - ./www/html:/var/www/html
    restart: always
